# This is a basic workflow to help you get started with Actions

name: Test

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main, feature/* ]

jobs:
  build-ios-debug:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - name: Run iOS
      run: flutter build ios --debug --no-codesign --flavor development --target lib/main.dev.dart --no-sound-null-safety
  build-android-debug:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter build apk --debug --flavor development --target lib/main.dev.dart --no-sound-null-safety
  test:
    runs-on: macos-latest
    if: ${{ !contains(github.event.pull_request.title, '[Skip CI]') }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-java@v1
      with:
        java-version: '12.x'
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '2.5.3'
    - run: flutter pub get
    - run: flutter test 
